# Generated by Django 2.2.11 on 2020-03-14 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='historical_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='historical_period',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
