# Generated by Django 2.2.11 on 2020-03-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200314_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLoad',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('website', models.ForeignKey(db_column='website_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Website')),
            ],
            options={
                'db_table': 'website_load',
                'managed': True,
            },
        ),
    ]
